name: Nightly Build

on:
  schedule:
    # Run every day at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  nightly-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: ['1.20', '1.21', '1.22']
        
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install cmake

    - name: Setup MSVC (Windows)
      if: matrix.os == 'windows-latest'
      uses: microsoft/setup-msbuild@v1.3

    - name: Build and test
      run: |
        mkdir build
        cd build
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          cmake .. -G "Visual Studio 17 2022" -A x64
          cmake --build . --config Release
        else
          cmake ..
          make
        fi
        cd ..
        go mod tidy
        go test -v
      shell: bash

    - name: Report status
      if: failure()
      run: |
        echo "Nightly build failed for ${{ matrix.os }} with Go ${{ matrix.go-version }}"
